config/routes.rb
Journalgraph::Application.routes.draw do

  resources :articles

  match '/query' => 'articles#search'

  match '/showall' => 'articles#show_all'
  match '/getrelated' => 'articles#get_related'
  match '/getauthors' => 'articles#show_authors'

  match '/getworks' => 'articles#get_works'

  match '/getrelatedauthors' => 'articles#get_related_authors'

  match '/search' => 'articles#handleQuery'
  root to: 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :arxiv_id, :arxiv_url, :published_date, :summary, :title, :update_date, :journal_ref, :doi, :comment, :category, :keywords, :pagerank

  has_many :creations
  has_many :authors, :through => :creations
  
	has_many :friendships
	has_many :friends, :through => :friendships, :uniq => true
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user
end

app/controllers/articles_controller.rb
require 'awesome_print'
require 'levenshtein'
require 'tf_idf'

class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index    

  end

  def show_all
    @articles = Article.all
    render "articles"
  end


  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end


  def score(article_tf,terms,idf)
    tf_score = 0
    idf_score = 0

    if idf
      terms.each do |term|
        if article_tf[term]
          tf_score += article_tf[term]
        end
        if article_tf[term]
          idf_score += idf[term]
        end
      end
      return tf_score*idf_score
    else
      terms.each do |term|
        if article_tf[term]
          tf_score += article_tf[term]
        end
      end
      return tf_score
    end
  end

  ### This function is called when 'magic' button is clicked

  def search
    query = params['query']       # query sent by user
    searchtype = params['searchtype']   # what type of search is this
    
    # based on search type, call the appropriate search function

    case searchtype
      when 'boolean' then @articles = search_bool(query)
      when 'tf' then @articles = search_TF(query)
      when 'tfidf' then @articles = search_TFIDF(query)
      when 'pagerank' then @articles = search_pagerank(query)
      when 'pageranktfidf' then @articles = search_TFIDF_pagerank(query)
      else @articles = nil
    end

    ap @articles
    @found = 1
    if @articles.nil?
      @msg = "None found, try again..."
      @found = 0
      @articles = []
    end
    render "articles"
    
  end

  # simple boolean search for whether query terms exist in the summary of articles

  def search_bool(query)
    ap "!!!!!!!!!!!!!!!!!!! SEARCH BOOL CALLED WITH query " + query.to_s
    terms = query.split(' ')

    articles_bool = []
    terms.each do |term|
      ap "!!!!!! TERM !!!!"
      ap term
      matches = Article.find(:all, conditions: ['summary LIKE ? and title LIKE ?', "%#{term}%", "%#{term}%"])
      ap "!!!!!!!! MATCHES !!!!!"
      ap matches
      matches.each do |article|
        if !articles_bool.include? article
          articles_bool << article
        end
      end
    end

    return articles_bool
    
  end

  # search based on Term frequency

  def search_TF(query)
    terms = query.split(' ')
    puts terms
    articles_bool = search_bool(query)    # first get a simple boolean search of articles


    # create the corpus of articles 
    corpus = []
    articles_bool.each do |article|
      summary = article.summary
      split_summary = summary.split(' ')
      corpus << split_summary
    end

    analyzed = nil

    # make a hash of TF for each of the articles 
    score_map = {}
    articles_bool.each do |article|
      summary = article.summary
      split_summary = summary.split(' ')
      article_tf = TfIdf.new([split_summary])
      score_map[article] = score(article_tf.tf[0],terms,analyzed)
    end

    # rank this hash by TF and return the articles

    @articles = articles_bool.sort_by { |article|
      -score_map[article]
    }

    return @articles
    
  end


  # TFIDF based search 

  def search_TFIDF(query)
    terms = query.split(' ')
    puts terms
    articles_bool = search_bool(query)


    # make a corpus
    corpus = []
    articles_bool.each do |article|
      summary = article.summary
      split_summary = summary.split(' ')
      corpus << split_summary
    end

    # get IDF values using TFIdf library
    analysis = TfIdf.new(corpus)
    analyzed = analysis.idf


    # get TfIdf scores for each of the articles into a hash

    score_map = {}
    articles_bool.each do |article|
      summary = article.summary
      split_summary = summary.split(' ')
      article_tf = TfIdf.new([split_summary])
      score_map[article] = score(article_tf.tf[0],terms,analyzed)
    end

    # rank by the score and return articles

    @articles = articles_bool.sort_by { |article|
      -(score_map[article])
    }

    return @articles
    
  end


  # Page rank search

  def search_pagerank(query)
    terms = query.split(' ')
    puts terms
    articles_bool = search_bool(query)  # get boolean matches first

    # rank these based on page rank vector

    @articles = articles_bool.sort_by { |article|
      pagerank = article.pagerank   # page rank is a model attribute since its is a independent of the query
      puts pagerank
      -(pagerank)
    }
    return @articles
  end


  # Page rank and TfIdf search

  def search_TFIDF_pagerank(query)
    terms = query.split(' ')
    puts terms
    articles_bool = search_bool(query)  # get boolean articles first

    corpus = []

    # make the corpus 

    articles_bool.each do |article|
      summary = article.summary
      split_summary = summary.split(' ')
      corpus << split_summary
    end

    # get TFIDF article hash

    analysis = TfIdf.new(corpus)
    analyzed = analysis.idf

    score_map = {}
    articles_bool.each do |article|
      summary = article.summary
      split_summary = summary.split(' ')
      article_tf = TfIdf.new([split_summary])
      score_map[article] = score(article_tf.tf[0],terms,analyzed)
    end

    # get pankrank values and sort on the sum of TfIdf and pagerank
    @articles = articles_bool.sort_by { |article|
      pagerank = article.pagerank
      puts pagerank
      -(score_map[article]+pagerank)
    }

    return @articles
    
  end


  # called when show_authors_papers is called on the client

  def get_works
    tag = params['query']

    @articles = get_articles(tag)
    
    @found = 1  
    if @articles.nil?
      @msg = "None found, try again..."
      @found = 0
      @articles = []
    end

    render "articles"

  end

  # helper function with gets articles based on author id

  def get_articles(author_id)

    @author = Author.find(author_id)

    @articles = []
    @author.creations.each do |creation|
      temp = Article.find(creation.article_id)

      if !@articles.include? temp
        @articles << Article.find(creation.article_id)
      end

    end
    # puts "ARTICLES"

    # ap @articles

    return @articles
  end


  # gets all authors of a certain article

  def show_authors
    tag = params['query']

    @article = Article.where('arxiv_id = ?', tag).first
    @authors = @article.authors
    # puts authors

    @found = 1
    if @authors.nil?
      @msg = "None found, try again..."
      @found = 0
      @authors = []
    end

    render "authors"
  end    


  # called when get related authors is called

  def get_related_authors
    tag = params['query']

    @articles = get_articles(tag)   # gets all articles of this author
    # puts 'ARTICLES'
    # ap @articles

    @related_articles = []
    @authors = []

    # for each of the author's articles, get 1st degree articles and their respective authors
    @articles.each do |article|
      puts "ARTIClE ID "
      puts article.arxiv_id
      getRelatedPapers(article.arxiv_id, -1).each do |related|

        authors = related.authors
        authors.each do |author|

          if !@authors.include?(author)
            @authors << author
          end

        end
      end
    end
    

    @found = 1
    if @authors == []
      @msg = "None found, try again..."
      @found = 0
    end

    render "authors"
  end    

  # called  when get related papers is called on client

  def get_related
    tag = params['query']


    @articles = getRelatedPapers(tag, -1)
    @found = 1
    if @articles.nil?
      @msg = "None found, try again..."
      @found = 0
      @articles = []
    end

    render "articles"
  end

  # helper function takes in id of the article passed in by client, and n which is number of articles to be returned

  def getRelatedPapers(curr_id, n)
    @article = Article.where('arxiv_id = ?', curr_id).first   # get the article passed in from DB
    
    puts @article
    if @article == [] || @article.nil?
      puts 'articles NOT found'
      return nil
    end
    @valid_friends = []

    @friends = @article.friendships # this returns all 1 degree close articles

    # if they are in the same category, store in valid friends
    @friends.each do |friendship|
      friend = Article.find(friendship.friend_id)
      if friend.category == @article.category
        @valid_friends << friend
      end
    end

    # get all inwards edges for this artcle
    Friendship.find(:all, conditions: {friend_id: @article.id}).each do |cited_by|
      @valid_friends << Article.find(cited_by.article_id)
      puts 'ADDED CITED BY'
    end

    puts "valid_friends"
    puts @valid_friends

    if @valid_friends == []
      puts 'NO VALID FRIENDS'
      return nil
    end

    temp = Hash.new()

    # Make a hash for each of these filtered articles
    # the key for this hash the score, and value is the article

    @valid_friends.each do |friend|
      keywords = @article.keywords.split(',')
      friend_keywords = friend.keywords.split(',')
      score = get_score(keywords, friend_keywords)
      puts "SCORE"
      puts score

      if !temp[score]
        temp[score] = []
      end
      temp[score] << friend
    end

    @final_articles = []

    # puts "TEMP SORT"
    # ap temp

    sorted = temp.dup

    # sort based on the score and return the articles.

    sorted.sort.each do |score|


        temp[score[0]].each do |article|
          puts "ARTICLE"
          puts article
          if !@final_articles.include? article
            if article.id != @article.id
              @final_articles << article
            end
          end
        end

    end
    puts "FINAL"
    puts @final_articles


    if n == -1
      return @final_articles
    else 
      return @final_articles.first(n)
    end

  end

  # gets the Levenshtein distance between the 2 keyword arrays. 

  def get_score(arr1, arr2)
    score = 0

    min = arr1

    if arr2.length < arr1.length

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/articles.html.erb
<div id="articles">


  <% if @articles != [] %>

    <table>
      <tr class="row">
        <th class="span2"> id </th>
        <th class="span5">Title</th>
        <th class="span2">Arxiv url</th>
        <!-- <th class="span4">Authors </th> -->
        <th class="span5">Summary</th>

      </tr>
     
      <% @articles.each do |article| %>
        <tr class="row <%= cycle('evenrow', 'oddrow') -%>" id="<%= article.arxiv_id%>">
          <td class="span2"><%= article.id %></td>
          <td class="span5"><%= article.title %></td>
          <td class="span2"><%= link_to "View Paper", article.arxiv_url %></td>


          <td class="span5"><%= truncate(article.summary, length: 300) %></td>

          <td class="span4">
            <button class="btn related" id= "<%=article.arxiv_id%>"> View Related Papers </button> 
            <button class="btn show_authors" id= "<%=article.arxiv_id%>"> Show All Authors </button>
          </td>

          
        </tr>  
      <% end %>
    </table>

  <% else %>

  <h1> <%= @msg %></h1>

  <% end %>



</div>

app/views/articles/authors.html.erb
<div id="authors">


  <% if @authors != [] %>

    <table>
      <tr class="row">
        <th class="span2"> Author id </th>
        <th class="span2"> Author Name </th>
      </tr>
     
      <% @authors.each do |author| %>
        <tr class="row <%= cycle('evenrow', 'oddrow') -%>" id="<%= author.id%>">
          <td class="span2"><%= author.id %></td>
          <td class="span2"><%= author.name %></td>
          <td class="span4">
            <button class="btn get_works_author" id="<%= author.id%>"> Get All papers </button>
            <button class="btn get_related_authors" id="<%= author.id%>"> Get Related Authors </button>
          </td>
        </tr>  
      <% end %>
    </table>

  <% else %>

  <h1> <%= @msg %></h1>

  <% end %>



</div>

app/views/articles/index.html.erb
<div class="hero-unit">
    <h1>Journal Graph</h1>
</div>

<div id="searchbox" class="row">
    <div class="span2">
        <input id="query" type="text" name="query" placeholder="Entry your request here...">
    </div>
    <div class="span2">
        <button class="btn magic"> Magic </button>
    </div>
    <div class="span5">
        <form>
            <input type="radio" name="search_type" id="boolean" checked> Boolean match
            <input type="radio" name="search_type" id="tf"> TF
            <input type="radio" name="search_type" id="tfidf"> TFIDF
            <input type="radio" name="search_type" id="pagerank"> PageRank
            <input type="radio" name="search_type" id="pageranktfidf"> TFIDF and PageRank
        </form>
    </div>

    <div class="span2">
    	<a href="#" id="showall"> Show All </a>
    </div>
</div>

<br><br><br>

<div class="results">

</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Arxiv:</b>
  <%= @article.arxiv_id %>
</p>

<p>
  <b>Arxiv url:</b>
  <%= @article.arxiv_url %>
</p>

<p>
  <b>Summary:</b>
  <%= @article.summary %>
</p>

<p>
  <b>Published date:</b>
  <%= @article.published_date %>
</p>

<p>
  <b>Update date:</b>
  <%= @article.update_date %>
</p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>